trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:

# =============================
# BUILD
# =============================
- stage: Build
  displayName: Build Application

  jobs:
  - job: BuildJob

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '9.x'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop



# =============================
# Staging DEPLOYMENT
# =============================
- stage: DeployStaging

  displayName: Deploy to Staging

  dependsOn: Build

  jobs:

  - deployment: StagingDeploy

    environment: Staging

    strategy:
      runOnce:

        deploy:

          steps:

          - download: current
            artifact: drop

          - task: AzureWebApp@1

            inputs:

              azureSubscription: 'WebAppDeploySubscription'
              appType: 'webApp'
              appName: 'DevopsAssignment3'

              deployToSlotOrASE: true

              resourceGroupName: 'DevopsTestPipeline'

              slotName: 'staging'

              package: '$(Pipeline.Workspace)/drop/**/*.zip'
# =============================
# Production DEPLOYMENT
# =============================
- stage: DeployProduction

  displayName: Deploy to Production

  dependsOn: DeployStaging

  jobs:

  - deployment: ProductionDeploy

    environment: Production

    strategy:
      runOnce:

        deploy:

          steps:

          - download: current
            artifact: drop

          - task: AzureWebApp@1

            inputs:

              azureSubscription: 'WebAppDeploySubscription'
              appType: 'webApp'
              appName: 'DevopsAssignment3'

              deployToSlotOrASE: true

              resourceGroupName: 'DevopsTestPipeline'

              slotName: 'production'

              package: '$(Pipeline.Workspace)/drop/**/*.zip'